# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hRp4nSYrm7-qcbsE4ByobOcm9g_RmUz-
"""

import networkx as nx
import matplotlib.pyplot as plt

# Створення пустого графа
G = nx.Graph()

# Додавання вершин (міст)
cities = ['Люксембург', 'Бородянка', 'Конотоп', 'Харків', 'Дніпро', 'Запоріжжя']
for city in cities:
    G.add_node(city)

# Додавання ребер (дороги) та їх ваг (відстань або час подорожі)
# Наприклад, список ребер та їх ваг може бути у форматі (місто_1, місто_2, відстань_або_час)
roads = [('Люксембург', 'Бородянка', 550),
         ('Люксембург', 'Конотоп', 480),
         ('Люксембург', 'Харків', 480),
         ('Харків', 'Бородянка', 1010),
         ('Харків', 'Дніпро', 220),
         ('Дніпро', 'Конотоп', 480),
         ('Дніпро', 'Запоріжжя', 80),
         ('Конотоп', 'Запоріжжя', 470),
         ('Бородянка', 'Запоріжжя', 960)]

for road in roads:
    G.add_edge(road[0], road[1], weight=road[2])

# Малювання графа
pos = nx.spring_layout(G)  # Позиціонування вершин
nx.draw(G, pos, with_labels=True)  # Малювання графа з мітками вершин
labels = nx.get_edge_attributes(G, 'weight')  # Отримання ваг ребер
nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)  # Додавання ваг ребер
plt.show()

import networkx as nx
import matplotlib.pyplot as plt

# Створення графа (код створення графа із попереднього відповіді)

# Візуалізація графа
pos = nx.spring_layout(G)  # Позиціонування вершин
nx.draw(G, pos, with_labels=True)  # Малювання графа з мітками вершин
labels = nx.get_edge_attributes(G, 'weight')  # Отримання ваг ребер
nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)  # Додавання ваг ребер
plt.title("Транспортна мережа міста")
plt.show()

# Аналіз основних характеристик графа
print("Кількість вершин (міст):", G.number_of_nodes())
print("Кількість ребер (доріг):", G.number_of_edges())

# Розрахунок та вивід ступенів вершин
degrees = dict(G.degree())
print("\nСтупені вершин:")
for city, degree in degrees.items():
    print(f"{city}: {degree}")